#Version should be chosen depending on you pp requirenments and need. 
#All version mentioned here: https://docs.docker.com/compose/compose-file/compose-versioning/
#for the education purpose version 3 will be enought
version: "3"
services: 
  api:
    image: artvictory/fastapi #current directory 
    depends_on: 
      - postgres #This command says that I want start the postgress container before the api starts
    #command: bash -c "alembic upgrade head" && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    # depends_on:
    #   - postgres
    ports: [80:8000] #as an example 
    #   #- 8000:8000 #<localhost port>:<dockerhost port>
    # env_file: 
    #   - ./.env
    volumes: 
      - ./:/usr/src/app:ro # this part consist of three parts: ./ - means our directory
      #/usr/src/app - means the path in the container where it runc  
      #ro - mens read only. Additional security feature that prevents any changes 
      #to the app from the part of container 
    environment: 
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME} #Grab from env. variable from dev machine
      - DATABASE_PORT=5432${DATABASE_PORT} # there is should be a env. variable name in the curly braces
      - DATABASE_PASSWORD=${DATABASE_PASSWORD} #production variable and actual env. variable names can differ 
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCES_TOKEN_EXPIRE_MINUTES=${ACCES_TOKEN_EXPIRE_MINUTES}


#Step 1: Create additional service in docker-compose.yml
#Step 2: Search requirenments to this service at https://hub.docker.com/_/postgres
  postgres:
    image: postgres #As named on the website 
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD} # we can give anything we want 
      - POSTGRES_DB=${DATABASE_NAME} # the same name as we were using in our development environment

#set the path where all data will be stored even if we kill the container 
    volumes: 
      - postgres-db:/var/lib/postgresql/data

#create global postgres data storage so we can reach the same DB from different containers
#and test different containers using one datatbase 
volumes:
  postgres-db:



