name: Build and Deploy File 

on: [push, pull_request]
  # push: 
  #   branches: 
  #     - "main"
  #     - "branch2"
  #     - "branch3"

  # pull_request:
  #   branches: 
  #     - ....
jobs:
  job1:
    env: 
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: 123
      DATABASE_NAME: fastapi
      DATABASE_USERNAME: postgres
      SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
    runs-on: ubuntu-20.04
    steps:
      - name: pulling git repo 
        uses: actions/checkout@v2
      - name: install python version 3.9 # We can install many other versions and also check whether
      #they work on other machines.
        uses: actions/setup-python@v2 #the same as sudo apt install python
        with:
          python-version: "3.9"
      - name: update pip 
        run: python -m pip install --upgrade pip
      - name: install all dependencies 
        run: pip install -r requirenments.txt
      - name: installing pytest
        run: pip install pytest
      - name: testing
        run: pytest -v -s


